import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { items, itemTranscripts } from "@/db/schema";
import { eq } from "drizzle-orm";
import { checkApiKey } from "@/lib/api-key";
import { rateLimit } from "@/lib/rate-limit";
import { extractYouTubeId, fetchYouTubeTranscriptResult, type TranscriptFetchFailure } from "@/lib/youtube";

// YouTube caption probes run before the Apify fallback, whose cold start can
// take more than a minute. Keep enough headroom for both stages.
export const maxDuration = 120;

const TRANSCRIPT_ERRORS: Record<TranscriptFetchFailure, string> = {
  "invalid-video": "This card has no valid YouTube video URL.",
  "fallback-not-configured": "The transcript fallback is not configured. Add APIFY_API_TOKEN and redeploy.",
  "fallback-auth": "The transcript provider rejected its API token. Update APIFY_API_TOKEN and redeploy.",
  "fallback-quota": "The transcript provider has reached its usage limit. Check the Apify account and try again.",
  "fallback-timeout": "The transcript provider took too long. Please try Fetch again.",
  "fallback-unavailable": "The transcript provider is temporarily unavailable. Please try again.",
  "no-transcript": "No transcript was found for this video. It may be private, unavailable, or have captions disabled.",
};

/**
 * GET /api/transcript?itemId=<uuid>
 *
 * Returns the stored transcript, or { transcript: null } when there isn't one.
 * Transcripts live outside the `items` row (see db/schema.ts) so the grid's
 * list read never carries them — this endpoint is the only thing that loads
 * the text, and only for a card the user has open.
 */
export async function GET(req: NextRequest) {
  const denied = checkApiKey(req);
  if (denied) return denied;

  const itemId = new URL(req.url).searchParams.get("itemId");
  if (!itemId) return NextResponse.json({ error: "Missing itemId" }, { status: 400 });

  const [row] = await db.select().from(itemTranscripts).where(eq(itemTranscripts.itemId, itemId));
  return NextResponse.json({ transcript: row || null });
}

/**
 * POST /api/transcript
 * Body: { id: "item-uuid" }
 *
 * Fetches the video's transcript and stores it. Tries YouTube's own caption
 * tracks first (free); falls back to an Apify actor, which bills per
 * successful transcript. Re-running replaces the stored row.
 */
export async function POST(req: NextRequest) {
  const denied = checkApiKey(req);
  if (denied) return denied;

  const ip = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown";
  const { allowed } = rateLimit(ip);
  if (!allowed) return NextResponse.json({ error: "Too many requests" }, { status: 429 });

  const { id } = await req.json().catch(() => ({ id: null }));
  if (!id) return NextResponse.json({ error: "Missing id" }, { status: 400 });

  const [item] = await db.select().from(items).where(eq(items.id, id));
  if (!item) return NextResponse.json({ error: "Item not found" }, { status: 404 });

  if (!item.url || !extractYouTubeId(item.url)) {
    return NextResponse.json({ error: "This card has no YouTube video URL" }, { status: 422 });
  }

  const result = await fetchYouTubeTranscriptResult(item.url);
  const transcript = result.transcript;
  if (!transcript?.text) {
    return NextResponse.json({
      error: TRANSCRIPT_ERRORS[result.failure || "fallback-unavailable"],
    }, { status: 422 });
  }

  const row = {
    itemId: id,
    text: transcript.text,
    source: transcript.source,
    language: transcript.languageCode || null,
    isAutoGenerated: transcript.isAutoGenerated,
    charCount: transcript.text.length,
    fetchedAt: new Date(),
  };

  const [saved] = await db
    .insert(itemTranscripts)
    .values(row)
    .onConflictDoUpdate({ target: itemTranscripts.itemId, set: row })
    .returning();

  return NextResponse.json({ transcript: saved });
}

/**
 * DELETE /api/transcript?itemId=<uuid> — drops a stored transcript.
 */
export async function DELETE(req: NextRequest) {
  const denied = checkApiKey(req);
  if (denied) return denied;

  const itemId = new URL(req.url).searchParams.get("itemId");
  if (!itemId) return NextResponse.json({ error: "Missing itemId" }, { status: 400 });

  await db.delete(itemTranscripts).where(eq(itemTranscripts.itemId, itemId));
  return NextResponse.json({ ok: true });
}
