"use client";

import { useCallback, useEffect, useState } from "react";
import { showToast } from "../Toast";
import { copyToClipboard } from "@/lib/clipboard";

export interface StoredTranscript {
  itemId: string;
  text: string;
  source: "youtube-captions" | "apify";
  language: string | null;
  isAutoGenerated: boolean;
  charCount: number;
  fetchedAt: string;
}

// Client-side "is this a video card" check. /api/transcript re-checks
// authoritatively with extractYouTubeId; this only decides whether to render
// the section, and is kept local so the server-only youtube module stays out
// of the client bundle.
const YOUTUBE_URL_RE = /(?:youtube\.com|youtu\.be)\//i;

export function isVideoUrl(url: string | null | undefined): boolean {
  return YOUTUBE_URL_RE.test(url || "");
}

function formatStamp(value: string | null | undefined): string {
  if (!value) return "";
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return "";
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")} ${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

interface TranscriptSectionProps {
  itemId: string;
  /** "panel" is the standalone box on the card page; "inline" matches the
   *  expanded grid card's other sections (top rule, no surrounding box). */
  variant?: "panel" | "inline";
}

export function TranscriptSection({ itemId, variant = "panel" }: TranscriptSectionProps) {
  const [transcript, setTranscript] = useState<StoredTranscript | null>(null);
  // Starts true: there is always an initial read, and defaulting to false makes
  // the first render — before the effect fires — claim there's no transcript and
  // offer a paid fetch for a card that already has one.
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [open, setOpen] = useState(false);

  const inline = variant === "inline";

  // Inside the expanded grid card the whole card body is a click target that
  // collapses it, so every control here has to stop the event escaping.
  const stop = (e: React.MouseEvent) => e.stopPropagation();

  const load = useCallback(async () => {
    // Must clear `loading` on this path too, or the section sticks on "Loading…".
    if (!itemId) { setLoading(false); return; }
    setLoading(true);
    try {
      const res = await fetch(`/api/transcript?itemId=${encodeURIComponent(itemId)}`);
      if (res.ok) {
        const data = await res.json() as { transcript?: StoredTranscript | null };
        setTranscript(data.transcript || null);
      }
    } catch {}
    setLoading(false);
  }, [itemId]);

  useEffect(() => { load(); }, [load]);

  const fetchTranscript = async () => {
    if (!itemId || busy) return;
    setBusy(true);
    try {
      const res = await fetch("/api/transcript", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: itemId }),
      });
      const data = await res.json().catch(() => ({} as { transcript?: StoredTranscript; error?: string }));
      if (res.ok && data.transcript) {
        setTranscript(data.transcript);
        setOpen(true);
        showToast("Transcript saved", "success");
      } else {
        showToast(data.error || "Couldn't fetch the transcript", "error");
      }
    } catch {
      showToast("Couldn't fetch the transcript", "error");
    }
    setBusy(false);
  };

  const copy = async () => {
    if (!transcript) return;
    const ok = await copyToClipboard(transcript.text);
    showToast(ok ? "Transcript copied" : "Couldn't copy the transcript", ok ? "success" : "error");
  };

  const remove = async () => {
    if (!itemId || !transcript) return;
    try {
      const res = await fetch(`/api/transcript?itemId=${encodeURIComponent(itemId)}`, { method: "DELETE" });
      if (!res.ok) { showToast("Couldn't remove the transcript", "error"); return; }
      setTranscript(null);
      setOpen(false);
      showToast("Transcript removed", "success");
    } catch {
      showToast("Couldn't remove the transcript", "error");
    }
  };

  return (
    <div
      onClick={stop}
      className={inline
        ? "mt-2.5 pt-2.5 border-t border-brand-border"
        : "mb-4 rounded-lg border border-brand-border bg-brand-muted"}
    >
      <div className={inline
        ? "flex items-center gap-2"
        : "flex items-center gap-2 px-3 py-2 border-b border-brand-border"}
      >
        <span className={inline
          ? "text-[10px] text-gray-600 font-mono"
          : "text-[11px] font-mono text-gray-400 tracking-wide"}
        >Transcript</span>
        {transcript && (
          <span className="text-[10px] font-mono text-gray-600">
            {transcript.charCount.toLocaleString()} chars
            {transcript.language ? ` · ${transcript.language}` : ""}
            {transcript.source === "apify" ? " · via Apify" : " · via YouTube captions"}
            {transcript.isAutoGenerated ? " · auto-generated" : ""}
          </span>
        )}
        <div className="flex-1" />
        {transcript && (
          <button
            type="button"
            onClick={e => { stop(e); copy(); }}
            className="text-[11px] font-mono text-gray-500 hover:text-gray-300 transition"
          >Copy</button>
        )}
        {transcript && (
          <button
            type="button"
            onClick={e => { stop(e); setOpen(o => !o); }}
            className="text-[11px] font-mono text-gray-500 hover:text-gray-300 transition"
          >{open ? "Hide" : "Show"}</button>
        )}
        {/* Withheld until the initial read settles. Rendering it mid-load shows
            "Fetch transcript" on a card that already has one, which reads as
            "nothing stored" and invites a pointless paid re-fetch. */}
        {!loading && (
          <button
            type="button"
            disabled={busy}
            onClick={e => { stop(e); fetchTranscript(); }}
            className="px-2 py-1 rounded-md text-[11px] font-mono transition hover:brightness-125 active:scale-95 disabled:opacity-50 flex items-center gap-1.5"
            style={{ border: "1px solid #6FCF9730", background: "#6FCF9710", color: "#6FCF97" }}
            title={transcript
              ? "Fetch the transcript again, replacing the stored copy"
              : "Fetch this video's transcript"}
          >
            {busy && <span className="inline-block w-3 h-3 border border-current border-t-transparent rounded-full" style={{ animation: "spin 0.6s linear infinite" }} />}
            {busy ? "Fetching…" : transcript ? "Re-fetch" : "Fetch transcript"}
          </button>
        )}
      </div>

      {loading && (
        <div className={inline ? "py-1.5 text-[11px] font-mono text-gray-600" : "px-3 py-2 text-[11px] font-mono text-gray-600"}>
          Loading…
        </div>
      )}

      {!loading && !transcript && (
        <div className={inline ? "py-1.5 text-[11px] font-mono text-gray-600" : "px-3 py-2 text-[11px] font-mono text-gray-600"}>
          No transcript stored yet. YouTube captions are free; if none exist it falls back to a
          paid fetch (about $0.01).
        </div>
      )}

      {transcript && open && (
        <>
          <textarea
            value={transcript.text}
            readOnly
            onClick={stop}
            aria-label="Video transcript"
            rows={inline ? 8 : 12}
            className={inline
              ? "mt-1.5 w-full rounded-md border border-brand-border bg-black/20 px-2 py-1.5 text-[11px] text-gray-400 outline-none resize-y leading-relaxed font-mono"
              : "w-full px-3 py-2 bg-transparent text-[12px] text-gray-400 outline-none resize-y leading-relaxed font-mono"}
          />
          <div className={inline
            ? "flex items-center gap-3 pt-1.5"
            : "flex items-center gap-3 px-3 py-2 border-t border-brand-border"}
          >
            <button
              type="button"
              onClick={e => { stop(e); copy(); }}
              className="text-[11px] font-mono text-gray-500 hover:text-gray-300 transition"
            >Copy</button>
            <button
              type="button"
              onClick={e => { stop(e); remove(); }}
              className="text-[11px] font-mono text-gray-500 hover:text-red-400 transition"
            >Remove</button>
            <div className="flex-1" />
            <span className="text-[10px] font-mono text-gray-700">
              fetched {formatStamp(transcript.fetchedAt)}
            </span>
          </div>
        </>
      )}
    </div>
  );
}
