export type TranscriptSource = "youtube-captions" | "apify";

export type YouTubeTranscript = {
  text: string;
  source: TranscriptSource;
  languageCode?: string;
  isAutoGenerated: boolean;
  trackName?: string;
};

export type TranscriptFetchFailure =
  | "invalid-video"
  | "fallback-not-configured"
  | "fallback-auth"
  | "fallback-quota"
  | "fallback-timeout"
  | "fallback-unavailable"
  | "no-transcript";

export type TranscriptFetchResult = {
  transcript: YouTubeTranscript | null;
  failure: TranscriptFetchFailure | null;
};

export function extractApifyTranscriptText(items: unknown): string {
  const records = Array.isArray(items) ? items : [items];
  for (const record of records) {
    const text = extractTranscriptTextFromValue(record);
    if (text) return normaliseTranscriptText(text);
  }
  return "";
}

export async function fetchApifyYouTubeTranscript(videoId: string): Promise<TranscriptFetchResult> {
  const token = process.env.APIFY_API_TOKEN;
  if (!token) return { transcript: null, failure: "fallback-not-configured" };

  const actor = (process.env.APIFY_YOUTUBE_TRANSCRIPT_ACTOR || "akash9078/youtube-transcript-extractor")
    .replace("/", "~");
  const endpoint = `https://api.apify.com/v2/acts/${actor}/run-sync-get-dataset-items?timeout=85`;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 88_000);

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({ videoUrl: `https://www.youtube.com/watch?v=${videoId}` }),
      signal: controller.signal,
    });
    if (response.status === 401 || response.status === 403) return { transcript: null, failure: "fallback-auth" };
    if (response.status === 402 || response.status === 429) return { transcript: null, failure: "fallback-quota" };
    if (!response.ok) return { transcript: null, failure: "fallback-unavailable" };

    const text = extractApifyTranscriptText(await response.json().catch(() => []));
    if (!text) return { transcript: null, failure: "no-transcript" };
    return {
      transcript: { text, source: "apify", isAutoGenerated: false, trackName: "Apify transcript" },
      failure: null,
    };
  } catch (error) {
    return {
      transcript: null,
      failure: error instanceof Error && error.name === "AbortError"
        ? "fallback-timeout"
        : "fallback-unavailable",
    };
  } finally {
    clearTimeout(timeout);
  }
}

export function decodeTranscriptEntities(value: string): string {
  return value
    .replace(/&#x([0-9a-f]+);/gi, (_, hex: string) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, decimal: string) => String.fromCodePoint(parseInt(decimal, 10)))
    .replace(/&quot;/g, "\"").replace(/&#39;|&apos;/g, "'")
    .replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
}

export function normaliseTranscriptText(value: string): string {
  return decodeTranscriptEntities(value)
    .replace(/\s+/g, " ")
    .replace(/\s+([,.!?;:])/g, "$1")
    .trim();
}

function extractTranscriptTextFromValue(value: unknown): string {
  if (!value) return "";
  if (typeof value === "string") return value;
  if (Array.isArray(value)) return value.map(extractTranscriptTextFromValue).filter(Boolean).join(" ");
  if (typeof value !== "object") return "";

  const record = value as Record<string, unknown>;
  for (const key of ["transcript", "transcriptText", "transcript_text", "fullText", "text", "segments", "captions", "chunks"]) {
    const text = extractTranscriptTextFromValue(record[key]);
    if (text) return text;
  }
  return "";
}
