export type YouTubeTranscript = {
  text: string;
  languageCode?: string;
  isAutoGenerated: boolean;
  trackName?: string;
};

export type YouTubeDescriptionLink = {
  url: string;
  label: string;
};

type CaptionTrack = {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  vssId?: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text?: string }>;
  };
};

const YOUTUBE_HEADERS = {
  "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
  "Accept-Language": "en-US,en;q=0.9",
};

const YOUTUBE_DESCRIPTION_LINKS_HEADER = "Links from YouTube description:";

export function extractYouTubeId(urlOrId: string): string | null {
  const value = urlOrId.trim();
  if (/^[a-zA-Z0-9_-]{11}$/.test(value)) return value;

  try {
    const url = new URL(value);
    const host = url.hostname.replace(/^www\./, "").replace(/^m\./, "").toLowerCase();

    if (host === "youtube.com" || host === "music.youtube.com") {
      const watchId = url.searchParams.get("v");
      if (watchId) return normaliseVideoId(watchId);

      const [kind, id] = url.pathname.split("/").filter(Boolean);
      if (["embed", "shorts", "live"].includes(kind) && id) return normaliseVideoId(id);
    }

    if (host === "youtu.be") {
      const id = url.pathname.split("/").filter(Boolean)[0];
      if (id) return normaliseVideoId(id);
    }
  } catch {}

  return null;
}

export function parseYouTubeTranscriptPayload(payload: string): string {
  const trimmed = payload.trim();
  if (!trimmed) return "";

  try {
    const data = JSON.parse(trimmed);
    const jsonText = parseJson3Transcript(data);
    if (jsonText) return jsonText;
  } catch {}

  return parseXmlTranscript(trimmed);
}

export async function fetchYouTubeTranscript(urlOrId: string): Promise<YouTubeTranscript | null> {
  const videoId = extractYouTubeId(urlOrId);
  if (!videoId) return null;

  const watchUrl = `https://www.youtube.com/watch?v=${videoId}&hl=en`;
  const html = await fetchText(watchUrl, YOUTUBE_HEADERS, 10_000);
  if (html) {
    const tracks = extractCaptionTracks(html);

    for (const track of rankCaptionTracks(tracks).slice(0, 5)) {
      if (!track.baseUrl) continue;

      const transcriptUrl = new URL(track.baseUrl);
      transcriptUrl.searchParams.set("fmt", "json3");

      const payload = await fetchText(transcriptUrl.toString(), YOUTUBE_HEADERS, 10_000);
      if (!payload) continue;

      const text = parseYouTubeTranscriptPayload(payload);
      if (text) {
        return {
          text,
          languageCode: track.languageCode,
          isAutoGenerated: isAutoGeneratedTrack(track),
          trackName: captionTrackName(track),
        };
      }
    }
  }

  return fetchApifyYouTubeTranscript(videoId);
}

export async function fetchYouTubeDescriptionLinks(urlOrId: string): Promise<YouTubeDescriptionLink[]> {
  const videoId = extractYouTubeId(urlOrId);
  if (!videoId) return [];

  const watchUrl = `https://www.youtube.com/watch?v=${videoId}&hl=en`;
  const html = await fetchText(watchUrl, YOUTUBE_HEADERS, 10_000);
  return html ? extractYouTubeDescriptionLinksFromHtml(html) : [];
}

export function extractYouTubeDescriptionLinksFromHtml(html: string): YouTubeDescriptionLink[] {
  const player = extractInitialPlayerResponse(html);
  return extractLinksFromYouTubeDescription(extractYouTubeDescriptionText(player));
}

export function extractLinksFromYouTubeDescription(description: string): YouTubeDescriptionLink[] {
  const links: YouTubeDescriptionLink[] = [];
  const seen = new Set<string>();

  for (const line of description.split(/\r?\n/)) {
    const matches = Array.from(line.matchAll(/https?:\/\/[^\s<>"')\]]+/gi));
    for (const match of matches) {
      const rawUrl = stripTrailingUrlPunctuation(match[0] || "");
      const url = normalizeYouTubeDescriptionUrl(rawUrl);
      if (!url || seen.has(url)) continue;

      seen.add(url);
      links.push({
        url,
        label: extractDescriptionLinkLabel(line, match.index ?? 0),
      });
    }
  }

  return links.slice(0, 12);
}

export function appendYouTubeDescriptionLinksToNotes(notes: string, links: YouTubeDescriptionLink[]): string {
  if (links.length === 0) return notes;
  if (notes.includes(YOUTUBE_DESCRIPTION_LINKS_HEADER)) return notes;

  const block = [
    YOUTUBE_DESCRIPTION_LINKS_HEADER,
    ...links.map((link) => link.label ? `- ${link.label}: ${link.url}` : `- ${link.url}`),
  ].join("\n");

  return [notes.trim(), block].filter(Boolean).join("\n\n");
}

export function extractApifyTranscriptText(items: unknown): string {
  const records = Array.isArray(items) ? items : [items];

  for (const record of records) {
    const text = extractTranscriptTextFromValue(record);
    if (text) return normaliseTranscriptText(text);
  }

  return "";
}

async function fetchApifyYouTubeTranscript(videoId: string): Promise<YouTubeTranscript | null> {
  const token = process.env.APIFY_API_TOKEN;
  if (!token) return null;

  const actor = (process.env.APIFY_YOUTUBE_TRANSCRIPT_ACTOR || "akash9078/youtube-transcript-extractor")
    .replace("/", "~");
  const endpoint = `https://api.apify.com/v2/acts/${actor}/run-sync-get-dataset-items?timeout=55`;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 55_000);

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        videoUrl: `https://www.youtube.com/watch?v=${videoId}`,
      }),
      signal: controller.signal,
    });

    if (!response.ok) return null;

    const items = await response.json().catch(() => []);
    const text = extractApifyTranscriptText(items);
    if (!text) return null;

    return {
      text,
      isAutoGenerated: false,
      trackName: "Apify transcript",
    };
  } catch {
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

function normaliseVideoId(value: string): string | null {
  const id = value.slice(0, 11);
  return /^[a-zA-Z0-9_-]{11}$/.test(id) ? id : null;
}

async function fetchText(url: string, headers: HeadersInit, timeoutMs: number): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(url, {
      headers,
      redirect: "follow",
      signal: controller.signal,
    });

    if (!response.ok) return "";
    return await response.text();
  } catch {
    return "";
  } finally {
    clearTimeout(timeout);
  }
}

function extractCaptionTracks(html: string): CaptionTrack[] {
  const player = extractInitialPlayerResponse(html);
  const tracks = player?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  return Array.isArray(tracks) ? tracks.filter((track): track is CaptionTrack => !!track?.baseUrl) : [];
}

function extractInitialPlayerResponse(html: string): any | null {
  const markers = [
    "ytInitialPlayerResponse =",
    "ytInitialPlayerResponse=",
    "window[\"ytInitialPlayerResponse\"] =",
  ];

  for (const marker of markers) {
    const json = extractJsonObjectAfter(html, marker);
    if (!json) continue;

    try {
      return JSON.parse(json);
    } catch {}
  }

  return null;
}

function extractJsonObjectAfter(source: string, marker: string): string | null {
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) return null;

  const start = source.indexOf("{", markerIndex);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < source.length; i += 1) {
    const char = source[i];

    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
    } else if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;
      if (depth === 0) return source.slice(start, i + 1);
    }
  }

  return null;
}

function rankCaptionTracks(tracks: CaptionTrack[]): CaptionTrack[] {
  return [...tracks].sort((a, b) => captionTrackScore(b) - captionTrackScore(a));
}

function captionTrackScore(track: CaptionTrack): number {
  const language = (track.languageCode || "").toLowerCase();
  const vssId = (track.vssId || "").toLowerCase();
  const isEnglish = language === "en" || language.startsWith("en-") || vssId.includes(".en");
  const isManual = !isAutoGeneratedTrack(track);

  return (isEnglish ? 100 : 0) + (isManual ? 10 : 0);
}

function isAutoGeneratedTrack(track: CaptionTrack): boolean {
  return track.kind === "asr" || (track.vssId || "").startsWith("a.");
}

function captionTrackName(track: CaptionTrack): string {
  if (track.name?.simpleText) return track.name.simpleText;
  return (track.name?.runs || []).map((run) => run.text || "").join("").trim();
}

function extractYouTubeDescriptionText(player: any): string {
  return [
    player?.videoDetails?.shortDescription,
    player?.microformat?.playerMicroformatRenderer?.description?.simpleText,
    player?.attributedDescription?.content,
  ].find((value) => typeof value === "string" && value.trim()) || "";
}

function stripTrailingUrlPunctuation(url: string): string {
  return url.replace(/[.,;:!?]+$/g, "");
}

function normalizeYouTubeDescriptionUrl(rawUrl: string): string {
  try {
    const parsed = new URL(rawUrl);
    const host = parsed.hostname.replace(/^www\./, "").replace(/^m\./, "").toLowerCase();
    const redirected = host === "youtube.com" && parsed.pathname === "/redirect"
      ? parsed.searchParams.get("q") || parsed.searchParams.get("url") || ""
      : "";

    const url = redirected ? new URL(redirected) : parsed;
    if (url.protocol !== "http:" && url.protocol !== "https:") return "";
    url.hash = "";
    return url.toString();
  } catch {
    return "";
  }
}

function extractDescriptionLinkLabel(line: string, urlIndex: number): string {
  const before = line
    .slice(0, urlIndex)
    .replace(/^[-*•\s]+/, "")
    .replace(/\s*(?:[:：\-–—|]\s*)$/g, "")
    .trim();

  if (!before || before.length > 80) return "";
  return before;
}

function parseJson3Transcript(data: any): string {
  if (!Array.isArray(data?.events)) return "";

  const text = data.events
    .map((event: any) => {
      if (!Array.isArray(event?.segs)) return "";
      return event.segs
        .map((segment: any) => typeof segment?.utf8 === "string" ? segment.utf8 : "")
        .filter((value: string) => value && value !== "\n")
        .join("")
        .trim();
    })
    .filter(Boolean)
    .join(" ");

  return normaliseTranscriptText(text);
}

function extractTranscriptTextFromValue(value: unknown): string {
  if (!value) return "";
  if (typeof value === "string") return value;

  if (Array.isArray(value)) {
    return value
      .map((item) => extractTranscriptTextFromValue(item))
      .filter(Boolean)
      .join(" ");
  }

  if (typeof value !== "object") return "";

  const record = value as Record<string, unknown>;
  for (const key of ["transcript", "transcriptText", "transcript_text", "fullText", "text"]) {
    const text = extractTranscriptTextFromValue(record[key]);
    if (text) return text;
  }

  for (const key of ["segments", "captions", "chunks"]) {
    const text = extractTranscriptTextFromValue(record[key]);
    if (text) return text;
  }

  return "";
}

function parseXmlTranscript(xml: string): string {
  const parts = Array.from(xml.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/gi))
    .map((match) => decodeEntities(stripTags(match[1] || "")));

  return normaliseTranscriptText(parts.join(" "));
}

function stripTags(value: string): string {
  return value.replace(/<[^>]+>/g, " ");
}

function decodeEntities(value: string): string {
  return value
    .replace(/&#x([0-9a-f]+);/gi, (_, hex: string) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, decimal: string) => String.fromCodePoint(parseInt(decimal, 10)))
    .replace(/&quot;/g, "\"")
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

function normaliseTranscriptText(value: string): string {
  return decodeEntities(value)
    .replace(/\s+/g, " ")
    .replace(/\s+([,.!?;:])/g, "$1")
    .trim();
}
